

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    targetFolder: '$(Build.ArtifactStagingDirectory)'    

- task: FlexNet Code Insight Scan@1
  inputs:
    URL: 'https://interneuron.netexsystems.com/codeinsight'
    Token: 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXR0QGludGVybmV1cm9uLm9yZyIsInVzZXJJZCI6MywiaWF0IjoxNTQ2NTM1MTYxfQ.W6CRa8SBRLukL3pz0_mVHNuKUKi47dAd_2hc9iMgljGurRVCgwSZvZoMZ78CTNdhRfr1tBiWY3zskCWHc-NsQg'
    ProjectName: 'Interneuron.Terminus'